title = "João Fraga's website"
baseURL = "https://fraguinha.com/"
languageCode = "en-us"

enableGitInfo = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]

[markup]
[markup.highlight]
noClasses = false
tabWidth = 2
style = ""
[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files

[privacy]
[privacy.googleAnalytics]
disable = false
anonymizeIP = true
respectDoNotTrack = true
[privacy.instagram]
disable = false
[privacy.twitter]
disable = false
enableDNT = true
[privacy.vimeo]
disable = false
enableDNT = true
[privacy.youtube]
disable = false
privacyEnhanced = true

[params]
description = "Software Engineer"
favicon = "/favicon.ico"
picture = "/fraguinha.png"
firstName = "João"
lastName = "Fraga"
nickname = "Fraguinha"
bio = "Currently working as a Software Engineer at Blip"
linkedin = "Fraguinha"
github = "Fraguinha"
email = "joao@fraguinha.com"
signal = "JReAop9nhikb7E17078qcICS0bq4GWdn5_mDh0XDSIgVGmB3wUJM2rg9hc6Lx5NS"
rss = "/index.xml"
cv = "/cv.pdf"
blog = "/post"
pgp = "/key.txt"
copyright = "Made by João Fraga @ fraguinha.com"
